wandb_project: ngram-llm-analysis

tokenizer_name: tokenizer  # should match vocab_size
vocab_size: 16384 # 65536 for u16 ngram trie

model_type: llama
hidden_size: 128
num_hidden_layers: 4
num_attention_heads: 4
intermediate_size: 512
max_position_embeddings: 2048
